version: 2
jobs:
  build:
    machine: true
    working_directory: ~/gravityflow
    steps:
      - checkout
      - run:
          name: Split the tests
          command: |
            circleci tests glob ~/gravityflow/tests/acceptance-tests/acceptance/[^_]*.php | circleci tests split | xargs -n 1 echo
            circleci tests glob ~/gravityflow/tests/acceptance-tests/acceptance/[^_]*.php | circleci tests split | xargs -n 1 echo >> ~/gravityflow/tests/acceptance-tests/_data/tests.txt
      - run:
          name: Run acceptance tests
          command: |
            docker-compose run --rm codeception run --html -vvv
      - store_artifacts:
          path: ~/gravityflow/tests/acceptance-tests/_output
          path: ~/gravityflow/tests/acceptance-tests/_data
