version: 2
jobs:
  build:
    machine: true
    working_directory: ~/gravityflow
    steps:
      - checkout
      - run:
          name: Split the tests
          command: |
            circleci tests glob "[^_]*.php" | xargs -n 1 echo
            circleci tests glob "[^_]*.php" | circleci tests split
      - run:
          name: Run acceptance tests
          command: |
            docker-compose run --rm codeception run --html -vvv
      - store_artifacts:
          path: ~/gravityflow/tests/acceptance-tests/_output
