version: 2
jobs:
  build:
    machine: true
    working_directory: ~/gravityflow
    steps:
      - checkout
      - run:
          name: Split the tests
          command: |
            mkdir ~/gravityflow/tests/acceptance-tests/acceptance/ci_split_tests
            circleci tests glob ~/gravityflow/tests/acceptance-tests/acceptance/[^_]*.php | circleci tests split | xargs -n 1 echo
            circleci tests glob ~/gravityflow/tests/acceptance-tests/acceptance/[^_]*.php | circleci tests split | xargs -n 1 cp ~/gravityflow/tests/acceptance-tests/acceptance/ci_split_tests
      - run:
          name: Run acceptance tests
          command: |
            docker-compose run --rm codeception run --html -vvv -o "groups: split-tests: tests/acceptance-tests/acceptance/ci_split_tests" -g split-tests
      - store_artifacts:
          path: ~/gravityflow/tests/acceptance-tests/_output
